version: 2.0
jobs:
  test:
    docker:
      - image: elixir:latest
    working_directory: ~/libsecp256k1
    steps:
      - run: apt-get update; apt-get -y install libtool autoconf libgmp3-dev
      - checkout:
          path: ~/libsecp256k1
      - restore_cache:
         keys:
           - v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
           - v1-dependency-cache-{{ arch }}
           - v1-dependency-cache
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix compile 
      - run: mix eunit
      - save_cache:
          key: v1-dependency-cache-{{ arch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps
            - ~/.mix

workflows:
  version: 2
  test:
    jobs:
      - test